from __future__ import annotations

import argparse
import json
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from typing import Any

from PIL import Image


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build crop assets for ObjectBank / RelationBank from precomputed manifests."
    )
    parser.add_argument(
        "--manifest_path",
        type=Path,
        required=True,
        help="Path to the jsonl or parquet manifest generated by prepare_vg_bank_manifest.py",
    )
    parser.add_argument(
        "--image_root",
        type=Path,
        required=True,
        help="Root directory for images referenced by image_rel_path in the manifest.",
    )
    parser.add_argument(
        "--output_dir",
        type=Path,
        required=True,
        help="Output root where crop files will be written.",
    )
    parser.add_argument(
        "--bank_type",
        choices=["object", "relation"],
        required=True,
        help="Which crop payloads to materialize.",
    )
    parser.add_argument(
        "--context_expand_ratio",
        type=float,
        default=0.15,
        help="How much to expand each side for object context crops.",
    )
    parser.add_argument(
        "--jpeg_quality",
        type=int,
        default=95,
        help="JPEG quality used when saving crops.",
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=8,
        help="Thread worker count for crop extraction.",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Optional cap for quick smoke runs.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing crop files if they already exist.",
    )
    return parser.parse_args()


def load_manifest(path: Path) -> list[dict[str, Any]]:
    if path.suffix == ".jsonl":
        records = []
        with path.open("r", encoding="utf-8") as fp:
            for line in fp:
                line = line.strip()
                if line:
                    records.append(json.loads(line))
        return records

    if path.suffix == ".parquet":
        import pandas as pd

        return pd.read_parquet(path).to_dict("records")

    raise ValueError(f"Unsupported manifest format: {path}")


def clamp_crop_box(box_xyxy: list[float], width: int, height: int) -> tuple[int, int, int, int]:
    x1, y1, x2, y2 = box_xyxy
    x1 = int(max(0, min(width, round(x1))))
    y1 = int(max(0, min(height, round(y1))))
    x2 = int(max(0, min(width, round(x2))))
    y2 = int(max(0, min(height, round(y2))))
    if x2 <= x1:
        x2 = min(width, x1 + 1)
    if y2 <= y1:
        y2 = min(height, y1 + 1)
    return x1, y1, x2, y2


def expand_box(box_xyxy: list[float], width: int, height: int, ratio: float) -> list[float]:
    x1, y1, x2, y2 = box_xyxy
    w = x2 - x1
    h = y2 - y1
    dx = w * ratio
    dy = h * ratio
    return [
        max(0.0, x1 - dx),
        max(0.0, y1 - dy),
        min(float(width), x2 + dx),
        min(float(height), y2 + dy),
    ]


def save_crop(image: Image.Image, crop_box_xyxy: list[float], save_path: Path, quality: int) -> None:
    save_path.parent.mkdir(parents=True, exist_ok=True)
    crop = image.crop(clamp_crop_box(crop_box_xyxy, *image.size))
    crop.save(save_path, quality=quality)


def process_object_record(
    record: dict[str, Any],
    image_root: Path,
    output_dir: Path,
    context_expand_ratio: float,
    jpeg_quality: int,
    overwrite: bool,
) -> None:
    image_path = image_root / record["image_rel_path"]
    tight_path = output_dir / record["tight_crop_rel_path"]
    context_path = output_dir / record["context_crop_rel_path"]
    if (not overwrite) and tight_path.exists() and context_path.exists():
        return

    with Image.open(image_path).convert("RGB") as image:
        tight_box = record["bbox_xyxy"]
        context_box = expand_box(tight_box, *image.size, ratio=context_expand_ratio)
        save_crop(image, tight_box, tight_path, quality=jpeg_quality)
        save_crop(image, context_box, context_path, quality=jpeg_quality)


def process_relation_record(
    record: dict[str, Any],
    image_root: Path,
    output_dir: Path,
    jpeg_quality: int,
    overwrite: bool,
) -> None:
    image_path = image_root / record["image_rel_path"]
    subj_path = output_dir / record["subj_crop_rel_path"]
    obj_path = output_dir / record["obj_crop_rel_path"]
    union_path = output_dir / record["union_crop_rel_path"]
    if (not overwrite) and subj_path.exists() and obj_path.exists() and union_path.exists():
        return

    with Image.open(image_path).convert("RGB") as image:
        save_crop(image, record["subj_bbox_xyxy"], subj_path, quality=jpeg_quality)
        save_crop(image, record["obj_bbox_xyxy"], obj_path, quality=jpeg_quality)
        save_crop(image, record["union_bbox_xyxy"], union_path, quality=jpeg_quality)


def main() -> None:
    args = parse_args()
    records = load_manifest(args.manifest_path)
    if args.limit is not None:
        records = records[: args.limit]

    if args.bank_type == "object":
        worker_fn = lambda rec: process_object_record(
            rec,
            image_root=args.image_root,
            output_dir=args.output_dir,
            context_expand_ratio=args.context_expand_ratio,
            jpeg_quality=args.jpeg_quality,
            overwrite=args.overwrite,
        )
    else:
        worker_fn = lambda rec: process_relation_record(
            rec,
            image_root=args.image_root,
            output_dir=args.output_dir,
            jpeg_quality=args.jpeg_quality,
            overwrite=args.overwrite,
        )

    with ThreadPoolExecutor(max_workers=args.workers) as executor:
        list(executor.map(worker_fn, records))

    summary = {
        "manifest_path": str(args.manifest_path),
        "bank_type": args.bank_type,
        "num_records": len(records),
        "output_dir": str(args.output_dir),
        "workers": args.workers,
        "overwrite": bool(args.overwrite),
    }
    summary_path = args.output_dir / f"{args.bank_type}_crop_build_summary.json"
    summary_path.parent.mkdir(parents=True, exist_ok=True)
    with summary_path.open("w", encoding="utf-8") as fp:
        json.dump(summary, fp, ensure_ascii=False, indent=2)
    print(json.dumps(summary, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
